version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/DockerfilePhp8
    tty: true
    external_links:
      - mysql
      - redis
    container_name: "${PROJECT_NAME_CALENDAR}_app"
    restart: on-failure
    working_dir: /usr/src/app
    volumes:
      - ./App:/usr/src/app:delegated
      - ./Config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      APP_URL: "${NGINX_URL_FRONT_CALENDAR}"
      L5_SWAGGER_CONST_HOST: "${NGINX_URL_FRONT_CALENDAR}"
      DB_PORT: "${MYSQL_PORT}"
      PROJECT_NAME: "${PROJECT_NAME_CALENDAR}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_USERNAME: root
      DB_HOST: mysql
      DB_DATABASE: "${MYSQL_DATABASE_CALENDAR}"
    networks:
      - network-calendar
      - mysql_network-mysql
      - redis_network-redis
  nginx:
    build:
      context: .
      dockerfile: Dockerfiles/DockerfileNginx
    container_name: "${PROJECT_NAME_CALENDAR}_app_nginx"
    restart: on-failure
    working_dir: /usr/src/app
    volumes:
      - ./App:/usr/src/app:delegated
      - ./Config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    expose:
      - "${NGINX_PORT_EXPOSE_CALENDAR}"
    ports:
      - "${NGINX_PORT_EXPOSE_CALENDAR}:80"
    environment:
      NGINX_HOST: "${NGINX_URL_FRONT_CALENDAR}"
      VIRTUAL_HOST: "${NGINX_URL_FRONT_CALENDAR}"
      LETSENCRYPT_HOST: "${NGINX_URL_FRONT_CALENDAR}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    networks:
      - network-calendar
      - proxy_reverse-proxy
  nginx_node:
    build:
      context: .
      dockerfile: Dockerfiles/DockerfileNode
      args:
        VUE_APP_BASE_URL: "http://${NGINX_URL_FRONT_CALENDAR}/api/"
    container_name: "${PROJECT_NAME_CALENDAR}_app_node_nginx"
    restart: on-failure
    working_dir: /usr/src/app
    depends_on:
      - app
    expose:
      - "${NGINX_PORT_EXPOSE_CALENDAR_NODE}"
    ports:
      - "${NGINX_PORT_EXPOSE_CALENDAR_NODE}:80"
    environment:
      NGINX_HOST: "${NGINX_URL_FRONT_CALENDAR_NODE}"
      VIRTUAL_HOST: "${NGINX_URL_FRONT_CALENDAR_NODE}"
      LETSENCRYPT_HOST: "${NGINX_URL_FRONT_CALENDAR_NODE}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    networks:
      - network-calendar
      - proxy_reverse-proxy
networks:
  network-calendar:
    driver: bridge
  proxy_reverse-proxy:
    external: true
  mysql_network-mysql:
    external: true
  redis_network-redis:
    external: true